

USE Markel
GO

CREATE TABLE Claims
(
UCR VARCHAR(20),
CompanyId INT,
ClaimDate DATETIME,
LossDate DATETIME,
[Assured Name] VARCHAR(100),
[Incurred Loss] DECIMAL(15,2),
Closed BIT
PRIMARY KEY CLUSTERED 
(
	[UCR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] 

go

CREATE TABLE ClaimType
(
Id INT,
Name VARCHAR(20)
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] 

go

CREATE TABLE Company
(
Id INT,
Name VARCHAR(200),
Address1 VARCHAR(100),
Address2 VARCHAR(100),
Address3 VARCHAR(100),
Postcode VARCHAR(20),
Country VARCHAR(50),
Active BIT,
InsuranceEndDate DATETIME
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] 

go